name       : sdl-gfx
version    : 2.0.25
release    : 3
source     :
    - http://netassist.dl.sourceforge.net/project/sdlgfx/SDL_gfx-2.0.25.tar.gz : 556eedc06b6cf29eb495b6d27f2dcc51bf909ad82389ba2fa7bdc4dec89059c0
license    : zlib
component  : multimedia.library
summary    : SDL graphics drawing primitives and other support functions
description: |
    SDL graphics drawing primitives and other support functions
builddeps  :
    - pkgconfig(sdl)
    - pkgconfig32(sdl)
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32     : yes
optimize   : speed
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
