name       : SDL_gfx
version    : 2.0.25
release    : 1
source     :
    - http://downloads.sourceforge.net/project/sdlgfx/SDL_gfx-2.0.25.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fsdlgfx%2F : 556eedc06b6cf29eb495b6d27f2dcc51bf909ad82389ba2fa7bdc4dec89059c0
license    : zlib # CHECK ME
summary    : SDL graphics drawing primitives and other support functions
description: |
        SDL graphics drawing primitives and other support functions
builddeps  : pkgconfig(sdl)
setup      : |
        %configure 
build      : |
    %make
install    : |
    %make_install
