name       : sdl-gfx
version    : 2.0.26
release    : 4
source     :
    - https://www.ferzkopp.net/Software/SDL_gfx-2.0/SDL_gfx-2.0.26.tar.gz : 7ceb4ffb6fc63ffba5f1290572db43d74386cd0781c123bc912da50d34945446
license    : Zlib
component  : multimedia.library
summary    : SDL graphics drawing primitives and other support functions
description: |
    SDL graphics drawing primitives and other support functions
builddeps  :
    - pkgconfig32(sdl)
emul32     : yes
optimize   : speed
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
